### ISSUE TITLE
Label für Lemmata, Beweise, Korollare, etc.

### ISSUE THREAD

**Issue by nebnola** [vale981/LAAG1#2]
Ich habe mir die Freiheit genommen, ein paar neue Label/Umgebungen/Wie-auch-immer-sich-das-nennt für häufig gebrauchte Sachen zu erstellen. Es gab ja schon vorher so etwas z.B. für Sätze, Definitionen, Beispiele. Deswegen wollte ich die mal zusammenstellen, mit der Bitte, die auch zu verwenden:

Format | Befehl
--------|--------
Beispiel|exa
Beweis|prof
Lemma|lemma
Proposition|proposition
Korollar|korollar
Beachte|notte
Notation|notation
Beobachtung|beobachtung
Bemerkung|bem

**Comment by vale981** [comment]
Tight ;)

**Comment by sammecs** [comment]
Habe mal eine Wiki-Seite dazu erstellt; Diskussionen über Konventionen können ja gerne in den Issues ausgetragen werden, aber ich denke, es ist auch gut, wenn man eine Seite hat, wo alles zusammengetragen wird.

**Comment by nebnola** [comment]
Danke, gute Idee! Eine Frage, warum ist `\(...\)` besser als `$...$`?

**Comment by sammecs** [comment]
Die Meinung eines Bloggers dazu ist [hier](http://texblog.net/latex-archive/maths/inline-math-mode/), eine StackOverflow-Diskussion dazu gibt es [hier](https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode). Zugegebenermaßen, der Unterschied ist nicht sehr groß, aber die `\(...\)`-Notation finde ich aus den Gründen, die der Blogger gebracht hat, schon irgendwie eleganter ;)

**Comment by vale981** [comment]
Bitte nicht text und math mischen...

**Comment by vale981** [comment]
`\( ... \)`  sind pain-in-the-ass :)

**Comment by sammecs** [comment]
Huh? Wieso? `\(...\)` sind die offizielle LaTeX-Schreibweise für die Einleitung des Mathe-Modus'.

**Comment by vale981** [comment]
Hard to type.

**Comment by sammecs** [comment]
Pff, mit TeXStudio und jedem anderen guten Editor geht das ohne Probleme. Kannst dir doch ein Makro einrichten.

**Comment by vale981** [comment]
true
