### ISSUE TITLE
Einteilung der Arbeit

### ISSUE THREAD

**Issue by sammecs** [vale981/LAAG1#3]
Hiho! Ich fände es gut, wenn man irgendwo einsehen könnte, wer gerade was macht. Einfach nur, um zu vermeiden, dass Aufgaben doppelt erledigt werden. Könnte man das auch mit Issues machen? Zum Beispiel, in dem man, bevor man mit der Arbeit anfängt, ein Issue zu der Aufgabe erstellt und sich selbst als "Assignee" einträgt. Vielleicht kann man das auch mit diesen ominösen GitHub-Projects machen. Sollte nur möglichst minimalistisch sein, damit die Hemmschwelle, etwas aufzuschreiben, möglichst gering bleibt. Wie seht ihr das?

Wir könnten auch eine WhatsApp-Gruppe dazu machen, aber dann würden sich bestimmt die vielen fleißigen außenstehenden Mitarbeiter, die noch nicht als Collaborators eingetragen sind, gar nicht trauen, ihre Pull requests zu senden.

**Comment by nebnola** [comment]
Dem schließe ich mich an. Issues zu benutzen, wäre vielleicht eine Möglichkeit, wenn auch nicht die eleganteste. Ich habe nur die Befürchtung, dass das nicht immer genutzt würde...

> die vielen fleißigen außenstehenden Mitarbeiter, die noch nicht als Collaborators eingetragen sind

wer bitte? ^^

**Comment by sammecs** [comment]
> wer bitte? ^^

Ich habe die Hoffnung nicht aufgegeben, dass es sie doch irgendwo da draußen gibt... ;)

**Comment by nebnola** [comment]
Naja, prinzipiell ist das nicht undenkbar. Nur ist die Hemmschwelle so hoch. Man muss nicht nur mit LaTeX umgehen können (das muss man früher oder später sowieso), sondern auch mit git (das ist wohl das eigentliche Problem). Vielleicht findet sich irgendein Weg, dass man auch Leuten, die damit nicht so versiert sind, Zugang ermöglicht. Denn wenn genügend Menschen etwas beitragen, dann muss jeder einzelne kaum noch etwas erledigen. Das wäre aber wohl Thema für ein anderes Issue...

**Comment by vale981** [comment]
Dazu war der online Editor gedacht.

Aber das ist vlt. Zu clumsy.

On 27 November 2017 20:47:32 CET, nebnola <notifications@github.com> wrote:
>Naja, prinzipiell ist das nicht undenkbar. Nur ist die Hemmschwelle so
>hoch. Man muss nicht nur mit LaTeX umgehen können (das muss man früher
>oder später sowieso), sondern auch mit git (das ist wohl das
>eigentliche Problem). Vielleicht findet sich irgendein Weg, dass man
>auch Leuten, die damit nicht so versiert sind, Zugang ermöglicht. Denn
>wenn genügend Menschen etwas beitragen, dann muss jeder einzelne kaum
>noch etwas erledigen. Das wäre aber wohl Thema für ein anderes Issue...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vale981/LAAG1/issues/3#issuecomment-347304437

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nebnola** [comment]
Hmm stimmt, den gab’s ja auch noch. Benutzt den jemand?
