### ISSUE TITLE
Alles ist kursiv

### ISSUE THREAD

**Issue by nebnola** [vale981/LAAG1#4]
Gefühlt ist ja das ganze Skript kursiv, weil fast alles Teil eines Beweises/einer Bemerkung etc. ist. Ich finde das ist unschön, und sieht an manchen Stellen lächerlich aus, wenn die Formeln das einzige sind, was nicht kursiv ist:
![Screenshot](https://user-images.githubusercontent.com/13544963/33294768-6702a87c-d3d2-11e7-8f75-3bc776c469de.png)

Ich finde, das sollte man abschaffen. Seid ihr meiner Meinung? Wie setzt man das um?

**Comment by vale981** [comment]
Ich füge ein neues Font Packet ein.

On 28 November 2017 00:26:27 CET, nebnola <notifications@github.com> wrote:
>Gefühlt ist ja das ganze Skript kursiv, weil fast alles Teil eines
>Beweises/einer Bemerkung etc. ist. Ich finde das ist unschön, und sieht
>an manchen Stellen lächerlich aus, wenn die Formeln das einzige sind,
>was nicht kursiv ist:
>![Screenshot](https://user-images.githubusercontent.com/13544963/33294768-6702a87c-d3d2-11e7-8f75-3bc776c469de.png)
>
>Ich finde, das sollte man abschaffen. Seid ihr meiner Meinung? Wie
>setzt man das um?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vale981/LAAG1/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sammecs** [comment]
Sollte man aber auch durch die Definition der Umgebungen ändern können. Ich versuche das mal fix.

**Comment by sammecs** [comment]
Ich denke auch, dass sich das Issue eher darauf bezog, dass der Text kursiv war und nicht die Mathematik. concmath sieht nicht schlecht aus, ich finde den LaTeX-Stil cooler (weil man Mathe und Text besser auseinander halten kann). Aber das ist nur meine Meinung, die objektiven Unterschiede sind nicht wesentlich. Was denkt ihr?

**Comment by vale981** [comment]
:smile:
