### ISSUE TITLE
ei Definition fehlt immer der erste Buchstabe

### ISSUE THREAD

**Issue by sammecs** [vale981/LAAG1#6]
as ist da los?
n der Box von den grünen Definitionen fehlt immer der erste Buchstabe.

**Comment by nebnola** [comment]
ie Definiton erwartet zwei Argumente: `\definition{Name}{label}` Aus irgendeinem Grund entscheidet sich Latex, wenn das zweite Argument fehlt, den ersten Buchstaben in der Box dafür zu nehmen. Das ist ungefähr so sinnvoll wie es klingt.
as ganze lässt sich beheben, wenn man leere geschweifte Klammern anfügt: `\definition{Name}{}`

**Comment by sammecs** [comment]
Komisch, aber tatsächlich: Es reicht nicht nur, `\begin{definition}{Name}` hinzuschreiben, man muss auch noch `\begin{definition}{Name}{}` hinklatschen. Aber dafür geht's jetzt.
